import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SideMenu from './components/_sideMenu';
import Content from './components/_content';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <main className="flex w-full h-full p-10 gap-4 max-sm:flex-col">
          <SideMenu />
          <Content>{children}</Content>
        </main>
      </body>
    </html>
  );
}
